// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxerkldcmnyhfhjonfeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZXJrbGRjbW55aGZoam9uZmVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MjgxOTEsImV4cCI6MjA1OTQwNDE5MX0.-PynIyHh2fgqXaoOHtlGTsVLpnqrXx6bkZBs4WVhCoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);